### DISCUSSION TITLE
No communication between the instances via redis broadcaster

### DISCUSSION THREAD

**Discussion by Koliham** [permitio/fastapi_websocket_pubsub#55] [Q&A]
I was able to run the pub/sub communication with a Javascript Frontend and the FastAPI backend all dockerized (yeah!).
But the current issue I have is when I scale the backend, that I have e.g. 4 instances.
In this case it seems like the instances are not communicating via the redis broadcaster. Instead each instance is just publishing notification to the clients which are directly connected to.
Any ideas what could be the reason?

//EDIT: Ok, I found the reason: The PubSubEndpoint had the wrong hostname for redis. I used "localhost", which works locally, but for production, I need to use the redis hostname from the docker compose file

<details>
  <summary><h3>Code</h3></summary>
  
  ```python
import asyncio
import uvicorn
from fastapi import FastAPI
from fastapi.routing import APIRouter
from fastapi_websocket_pubsub import PubSubEndpoint
from starlette.websockets import WebSocket

PORT = 8000

app = FastAPI()
router = APIRouter()
endpoint = PubSubEndpoint(broadcaster="redis://wsredis:6379") # was redis://localhost:6379 before

@router.websocket("/pubsub")
async def websocket_rpc_endpoint(websocket: WebSocket):
    async with endpoint.broadcaster:
        await endpoint.main_loop(websocket)

app.include_router(router)

async def events(topic: str = "NoTopic"):
    await endpoint.publish([topic], {"somekey": "SomeValue"})


@app.get("/trigger")
async def trigger_events():
    asyncio.create_task(events("topic1"))


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=PORT)

  ```
</details>

<details>
  <summary><h3>Docker Compose YAML</h3></summary>
  
  ```yaml
  wsbackend:
    image: mywsimage
    networks:
      - traefik-public
    depends_on:
      - wsredis
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wsbackend.rule=Host(`wsbackend.mydomain.de`)"
        - "traefik.http.routers.wsbackend.entrypoints=websecure"
        - "traefik.http.routers.wsbackend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.wsbackend.loadbalancer.server.port=80"
        - "traefik.http.services.wsbackend.loadBalancer.sticky.cookie.name=server_id"
        
  wsredis:
    image: redis:7
    networks:
      - traefik-public

  ```
</details>
